version: '2'
services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - "2181:2181"
  kafka:
    image: uni-search-engine/kafka:0.0.1-SNAPSHOT
    ports: ["9092:9092"]
    depends_on: [zookeeper]
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "web_events:1:1,search_events:1:1,select_search_result_events:1:1"
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
  searchEngineStreamProcessor:
    image: uni-search-engine/kafka:0.0.1-SNAPSHOT
    network_mode: "host"
    depends_on: [kafka]
    command: [ "/bin/bash", "-c", "sleep 15s && java -jar /opt/kafka/my_jars/search-engine-kafka-stream-processors.jar" ]
  nginx:
    image: nginx:latest
    volumes: [ "/opt/search-homepage-of-university-leipzig/nginx.conf:/etc/nginx/conf.d/default.conf" ]
    network_mode: "host"
  searchEngineFrontend:
    image: uni-search-engine/frontend:0.0.1-SNAPSHOT
    network_mode: "host"
  searchEngineBackend:
    image: uni-search-engine/backend:0.0.1-SNAPSHOT
    network_mode: "host"
    depends_on: [searchEngineStreamProcessor]
    volumes: ["/opt/full-index:/opt/search-engine/index"]
