version: '2'
services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:1.0.0
    ports: ["9092:9092"]
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "all_web_requests:1:1"
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
